version: '2'

services:
  sequelize:
    build: .
    links:
      - postgres-17
    volumes:
      - .:/sequelize
    environment:
      SEQ_DB: sequelize_test
      SEQ_USER: sequelize_test
      SEQ_PW: sequelize_test

  # PostgreSQL
  postgres-95:
    image: sushantdhiman/postgres:9.5
    environment:
      POSTGRES_USER: sequelize_test
      POSTGRES_PASSWORD: sequelize_test
      POSTGRES_DB: sequelize_test
    volumes:
      - /mnt/sequelize-postgres-ramdisk:/var/lib/postgresql/data
    ports:
      - '8998:5432'
    container_name: postgres-95

  # PostgreSQL 17
  postgres-17:
    platform: linux/amd64
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_USER: sequelize_test
      POSTGRES_PASSWORD: sequelize_test
      POSTGRES_DB: sequelize_test
    volumes:
      - ./test/config/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    ports:
      - '8996:5432'
    container_name: postgres-17
