module.exports = {
  entryPointStrategy: 'packages',
  entryPoints: [
    'packages/core',
    'packages/db2',
    'packages/ibmi',
    'packages/mariadb',
    'packages/mssql',
    'packages/mysql',
    'packages/oracle',
    'packages/postgres',
    'packages/snowflake',
    'packages/sqlite3',
    'packages/utils',
    'packages/validator-js',
  ],
  out: './.typedoc-build',
  readme: 'none',
  plugin: ['typedoc-plugin-missing-exports', 'typedoc-plugin-mdn-links'],
  treatWarningsAsErrors: true,
  highlightLanguages: ['typescript', 'sql', 'javascript', 'shellscript'],
};
