services:
  mysql-oldest:
    container_name: sequelize-mysql-oldest
    image: mysql:8.0.19
    environment:
      MYSQL_DATABASE: sequelize_test
      MYSQL_USER: sequelize_test
      MYSQL_PASSWORD: sequelize_test
      MYSQL_ROOT_PASSWORD: sequelize_test
    ports:
      - 20057:3306
    volumes:
      - mysql-oldest:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', '-usequelize_test', '-psequelize_test', 'status']
      interval: 3s
      timeout: 1s
      retries: 10

networks:
  default:
    name: sequelize-mysql-oldest-network

volumes:
  mysql-oldest:
    name: sequelize-mysql-oldest-volume
