# Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved

services:
  oracle-oldest:
    container_name: sequelize-oracle-oldest
    image: gvenzl/oracle-xe:18-slim
    environment:
      ORACLE_PASSWORD: password
    ports:
      - 1521:1521
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'echo "select 1 from dual;" | sqlplus -L -S system/password@localhost:1521/XEPDB1',
        ]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 120s

networks:
  default:
    name: sequelize-oracle-oldest-network
