blank_issues_enabled: false
contact_links:
  - name: 💬 Help & Questions
    url: https://github.com/sequelize/sequelize/discussions
    about: The issue tracker is for bug reports and feature requests. Use GitHub Discussions for question and help requests.
  - name: 🔧 Having issues with Sequelize CLI?
    url: https://github.com/sequelize/cli/issues
    about: The issue tracker is for Sequelize CLI issues.
  - name: 📗 Having issues with Sequelize documentation?
    url: https://github.com/sequelize/website/issues
    about: The issue tracker is for Sequelize documentation issues.
