services:
  oracledb-21c:
    container_name: oraclexedb21c
    image: gvenzl/oracle-xe:21.3.0-slim
    environment:
      ORACLE_PASSWORD: password
      APP_USER: sequelizetest
      APP_USER_PASSWORD: sequelizepassword
    ports:
      - 1521:1521
    healthcheck:
      test: ["CMD-SHELL", "sqlplus", "sequelizetest/sequelizepassword@XEPDB1"]
      retries: 10

networks:
  default:
    name: sequelize-oraclexedb21c-network
