'use strict';

const util = require('node:util');
const Support = require('../../../support');
const { DataTypes, Op, sql } = require('@sequelize/core');
const BaseTypes = require('@sequelize/core/_non-semver-use-at-your-own-risk_/abstract-dialect/data-types.js');
const {
  buildInvalidOptionReceivedError,
} = require('@sequelize/core/_non-semver-use-at-your-own-risk_/utils/check.js');
const { OracleQuery } = require('@sequelize/oracle');
const { expect } = require('chai');

const expectsql = Support.expectsql;
const current = Support.sequelize;
const queryGenerator = current.dialect.queryGenerator;

if (current.dialect.name === 'oracle') {
  describe('[Oracle Specific] VECTOR', () => {
    describe('VECTOR datatype', () => {
      it('creates table with vector datatype', () => {
        const FooUser = current.define('user', {
          embedding: {
            type: DataTypes.VECTOR,
            allowNull: false,
          },
        });

        expectsql(
          queryGenerator.createTableQuery(
            FooUser.table,
            queryGenerator.attributesToSQL(FooUser.getAttributes()),
            {},
          ),
          {
            default: `BEGIN EXECUTE IMMEDIATE 'CREATE TABLE "users" ("id" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, "embedding" VECTOR NOT NULL, "createdAt" TIMESTAMP WITH LOCAL TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,PRIMARY KEY ("id"))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`,
          },
        );
      });
    });

    describe('VECTOR datatype with dimension and format', () => {
      it('creates table with vector datatype', () => {
        const FooUser = current.define('user', {
          embedding: {
            type: DataTypes.VECTOR(3, 'float32'),
            allowNull: false,
          },
        });

        expectsql(
          queryGenerator.createTableQuery(
            FooUser.table,
            queryGenerator.attributesToSQL(FooUser.getAttributes()),
            {},
          ),
          {
            default: `BEGIN EXECUTE IMMEDIATE 'CREATE TABLE "users" ("id" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, "embedding" VECTOR(3, FLOAT32) NOT NULL, "createdAt" TIMESTAMP WITH LOCAL TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,PRIMARY KEY ("id"))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`,
          },
        );
      });
    });

    describe('Vector index', () => {
      it('default', () => {
        expectsql(queryGenerator.addIndexQuery('Foo', ['vec1'], { type: 'VECTOR' }), {
          default:
            'CREATE VECTOR INDEX "foo_vec1" ON "Foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH',
        });
      });

      it('defaults using to hnsw when not provided', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', {
            fields: ['vec1'],
            type: 'VECTOR',
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH',
          },
        );
      });

      it('sanitizes dotted and quoted prefixes when generating vector index names', () => {
        expectsql(
          queryGenerator.addIndexQuery('ignored', ['vec1'], {
            type: 'VECTOR',
            prefix: '"schema"."foo"',
          }),
          {
            default:
              'CREATE VECTOR INDEX "schema_foo_vec1" ON "ignored" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH',
          },
        );
      });

      it('accepts lowercase vector type', () => {
        expectsql(queryGenerator.addIndexQuery('Foo', ['vec1'], { type: 'vector' }), {
          default:
            'CREATE VECTOR INDEX "foo_vec1" ON "Foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH',
        });
      });

      it('accepts object-form index definition with lowercase vector type', () => {
        expectsql(
          queryGenerator.addIndexQuery('Foo', {
            fields: ['vec1'],
            type: 'vector',
            using: 'ivf',
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "Foo" ("vec1") ORGANIZATION NEIGHBOR PARTITIONS',
          },
        );
      });

      it('ivf with parameters and target accuracy', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 'ivf',
            accuracy: 95,
            parameter: { partitions: 5, samplesPerPartition: 10, minVectors: 10 },
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION NEIGHBOR PARTITIONS WITH TARGET ACCURACY 95 PARAMETERS (type ivf, NEIGHBOR PARTITIONS 5, SAMPLES_PER_PARTITION 10, MIN_VECTORS_PER_PARTITION 10)',
          },
        );
      });

      it('supports explicit vector distance metric', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            distance: 'COSINE',
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH WITH DISTANCE COSINE',
          },
        );
      });

      it('normalizes lowercase vector distance metric', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            distance: 'cosine',
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH WITH DISTANCE COSINE',
          },
        );
      });

      it('rejects unsupported vector index using values', () => {
        expect(() =>
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 'btree',
          }),
        ).to.throw(TypeError, 'Oracle VECTOR index using must be either "hnsw" or "ivf".');
      });

      it('rejects non-string vector index using values', () => {
        expect(() =>
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 123,
          }),
        ).to.throw(TypeError, 'Oracle VECTOR index using must be either "hnsw" or "ivf".');
      });

      it('accepts uppercase using value', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 'HNSW',
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH',
          },
        );
      });

      it('accepts uppercase ivf using value', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'vector',
            using: 'IVF',
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION NEIGHBOR PARTITIONS',
          },
        );
      });

      it('ignores ivf parameters when using hnsw', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 'hnsw',
            parameter: { partitions: 4 },
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH PARAMETERS (type hnsw)',
          },
        );
      });

      it('ignores hnsw parameters when using ivf', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 'ivf',
            parameter: { neighbor: 8 },
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION NEIGHBOR PARTITIONS PARAMETERS (type ivf)',
          },
        );
      });

      it('supports hnsw parameters in SQL', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 'hnsw',
            parameter: { neighbor: 8, efconstruction: 32 },
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION INMEMORY NEIGHBOR GRAPH PARAMETERS (type hnsw, neighbor 8, efconstruction 32)',
          },
        );
      });

      it('supports parallel degree in SQL', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            using: 'ivf',
            parallel: 4,
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec1" ON "foo" ("vec1") ORGANIZATION NEIGHBOR PARTITIONS PARALLEL 4',
          },
        );
      });

      it('rejects unsupported vector index options instead of ignoring them', () => {
        expect(() =>
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            unique: true,
          }),
        ).to.throw(buildInvalidOptionReceivedError('addIndexQuery', 'oracle', ['unique']).message);
      });

      it('rejects unsafe vector index distance fragments', () => {
        expect(() =>
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            distance: 'COSINE) PARAMETERS (type hnsw',
          }),
        ).to.throw(TypeError, 'Oracle VECTOR index distance must be one of');
      });

      it('rejects unsafe vector index accuracy fragments', () => {
        expect(() =>
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            accuracy: '95) PARAMETERS (type hnsw',
          }),
        ).to.throw(TypeError, 'Oracle VECTOR index accuracy must be a positive number.');
      });

      it('rejects unsafe vector index parameter fragments', () => {
        expect(() =>
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            parameter: { neighbor: '8) PARAMETERS (type ivf' },
          }),
        ).to.throw(TypeError, 'Oracle VECTOR index parameter.neighbor must be a positive integer.');
      });

      it('rejects unsafe vector index parallel fragments', () => {
        expect(() =>
          queryGenerator.addIndexQuery('foo', ['vec1'], {
            type: 'VECTOR',
            parallel: '4 PARAMETERS (type hnsw)',
          }),
        ).to.throw(TypeError, 'Oracle VECTOR index parallel must be a positive integer.');
      });

      it('rejects ordered vector index fields', () => {
        expect(() =>
          queryGenerator.addIndexQuery('foo', {
            fields: [{ name: 'vec1', order: 'DESC' }],
            type: 'VECTOR',
          }),
        ).to.throw(TypeError, 'Oracle VECTOR indexes do not support ordered fields.');
      });

      it('supports SQL expression index fields', () => {
        expectsql(
          queryGenerator.addIndexQuery('foo', {
            name: 'foo_vec_expr',
            fields: [sql.literal('LOWER("vec1")')],
            type: 'VECTOR',
          }),
          {
            default:
              'CREATE VECTOR INDEX "foo_vec_expr" ON "foo" (LOWER("vec1")) ORGANIZATION INMEMORY NEIGHBOR GRAPH',
          },
        );
      });

      it('throws when no fields are provided', () => {
        expect(() => queryGenerator.addIndexQuery('foo', [], { type: 'VECTOR' })).to.throw(
          Error,
          'Vector indexes require at least one indexed field.',
        );
      });

      it('throws when a vector index field has no name', () => {
        expect(() =>
          queryGenerator.addIndexQuery('foo', {
            fields: [{}],
            type: 'VECTOR',
          }),
        ).to.throw(Error, 'The following index field has no name');
      });
    });

    describe('showIndex metadata', () => {
      const buildQuery = () => new OracleQuery({}, current, {});

      it('reports vector method hnsw', () => {
        const query = buildQuery();
        const rows = [
          {
            INDEX_NAME: 'IDX_HNSW',
            INDEX_TYPE: 'VECTOR',
            INDEX_SUBTYPE: 'INMEMORY_NEIGHBOR_GRAPH_HNSW',
            ITYP_NAME: null,
            UNIQUENESS: 'NONUNIQUE',
            CONSTRAINT_TYPE: null,
            TABLE_NAME: 'FOO',
            COLUMN_NAME: 'EMBEDDING',
            DESCEND: null,
          },
        ];

        const result = query.handleShowIndexesQuery(rows);
        expect(result[0].method).to.equal('hnsw');
      });

      it('reports vector method ivf', () => {
        const query = buildQuery();
        const rows = [
          {
            INDEX_NAME: 'IDX_IVF',
            INDEX_TYPE: 'VECTOR',
            INDEX_SUBTYPE: 'NEIGHBOR_PARTITION_GRAPH_IVF',
            ITYP_NAME: null,
            UNIQUENESS: 'NONUNIQUE',
            CONSTRAINT_TYPE: null,
            TABLE_NAME: 'FOO',
            COLUMN_NAME: 'EMBEDDING',
            DESCEND: null,
          },
        ];

        const result = query.handleShowIndexesQuery(rows);
        expect(result[0].method).to.equal('ivf');
      });

      it('leaves method undefined when parameters missing', () => {
        const query = buildQuery();
        const rows = [
          {
            INDEX_NAME: 'IDX_UNKNOWN',
            INDEX_TYPE: 'VECTOR',
            ITYP_NAME: null,
            UNIQUENESS: 'NONUNIQUE',
            CONSTRAINT_TYPE: null,
            TABLE_NAME: 'FOO',
            COLUMN_NAME: 'EMBEDDING',
            DESCEND: null,
          },
        ];

        const result = query.handleShowIndexesQuery(rows);
        expect(result[0].method).to.equal(undefined);
      });

      it('maps NORMAL index type to undefined', () => {
        const query = buildQuery();
        const rows = [
          {
            INDEX_NAME: 'IDX_NORMAL',
            INDEX_TYPE: 'NORMAL',
            ITYP_NAME: null,
            UNIQUENESS: 'NONUNIQUE',
            CONSTRAINT_TYPE: null,
            TABLE_NAME: 'FOO',
            COLUMN_NAME: 'ID',
            DESCEND: null,
          },
        ];

        const result = query.handleShowIndexesQuery(rows);
        expect(result[0].type).to.equal(undefined);
      });

      it('keeps non-vector index types', () => {
        const query = buildQuery();
        const rows = [
          {
            INDEX_NAME: 'IDX_BITMAP',
            INDEX_TYPE: 'BITMAP',
            ITYP_NAME: null,
            UNIQUENESS: 'NONUNIQUE',
            CONSTRAINT_TYPE: null,
            TABLE_NAME: 'FOO',
            COLUMN_NAME: 'ID',
            DESCEND: null,
          },
        ];

        const result = query.handleShowIndexesQuery(rows);
        expect(result[0].type).to.equal('BITMAP');
      });
    });

    describe('VECTOR datatype override hooks', () => {
      it('converts array input to Float64Array bind values', () => {
        const type = DataTypes.VECTOR(3).toDialectDataType(current.dialect);
        const bindValue = type.toBindableValue([1, 2, 3]);

        expect(bindValue).to.be.instanceOf(Float64Array);
        expect(Array.from(bindValue)).to.deep.equal([1, 2, 3]);
      });

      it('keeps typed array input as-is for binding', () => {
        const type = DataTypes.VECTOR(3).toDialectDataType(current.dialect);
        const typed = new Float32Array([1, 2, 3]);

        expect(type.toBindableValue(typed)).to.equal(typed);
      });

      it('accepts SparseVector-like input and keeps it as-is for binding', () => {
        const type = DataTypes.VECTOR(5).toDialectDataType(current.dialect);
        const sparseVector = {
          values: new Float64Array([1, 2]),
          indices: new Uint32Array([2, 4]),
          numDimensions: 5,
        };

        expect(() => type.validate(sparseVector)).not.to.throw();
        expect(type.toBindableValue(sparseVector)).to.equal(sparseVector);
      });

      it('rejects invalid SparseVector-like input', () => {
        const type = DataTypes.VECTOR(5).toDialectDataType(current.dialect);

        expect(() =>
          type.validate({
            values: new Float64Array([1, 2]),
            indices: new Uint32Array([2]),
            numDimensions: 5,
          }),
        ).to.throw(Error, 'is not a valid vector');
      });

      it('returns the Oracle VECTOR bind definition', () => {
        const type = DataTypes.VECTOR(3).toDialectDataType(current.dialect);

        expect(type._getBindDef({ DB_TYPE_VECTOR: 'DB_TYPE_VECTOR' })).to.deep.equal({
          type: 'DB_TYPE_VECTOR',
        });
      });

      it('rejects unsupported Oracle VECTOR formats', () => {
        expect(() => DataTypes.VECTOR(3, 'int16').toDialectDataType(current.dialect)).to.throw(
          TypeError,
          'Invalid Oracle VECTOR format: int16',
        );
      });

      it('accepts Oracle binary format and renders BINARY in SQL', () => {
        const type = DataTypes.VECTOR(24, 'binary').toDialectDataType(current.dialect);

        expect(type.toSql()).to.equal('VECTOR(24, BINARY)');
      });

      it('renders object-style binary options in SQL', () => {
        const type = DataTypes.VECTOR({ dimension: 24, format: 'binary' }).toDialectDataType(
          current.dialect,
        );

        expect(type.toSql()).to.equal('VECTOR(24, BINARY)');
      });

      it('keeps object-style dimension-only SQL concise', () => {
        const type = DataTypes.VECTOR({ dimension: 24 }).toDialectDataType(current.dialect);

        expect(type.toSql()).to.equal('VECTOR(24)');
      });

      it('renders Oracle-specific sparse storage when using the Oracle VECTOR override directly', () => {
        const OracleVector = current.dialect.getDataTypeForDialect(BaseTypes.VECTOR);
        const type = new OracleVector({ dimension: 8, format: 'int8', storage: 'sparse' });

        expect(type.toSql()).to.equal('VECTOR(8, INT8, SPARSE)');
      });

      it('rejects unsupported Oracle VECTOR storage options', () => {
        const OracleVector = current.dialect.getDataTypeForDialect(BaseTypes.VECTOR);

        expect(() => new OracleVector({ dimension: 8, storage: 'dense' })).to.throw(
          TypeError,
          'Invalid Oracle VECTOR storage: dense',
        );
      });
    });

    describe('Vector where clause', () => {
      const queryVector = [1, 2, 3];

      const testsql = (key, value, options, expectation) => {
        if (expectation === undefined) {
          expectation = options;
          options = undefined;
        }

        const whereObj = sql.where(key, value);
        it(
          util.inspect(whereObj, { depth: 4 }) + (options ? `, ${util.inspect(options)}` : ''),
          () => {
            return expectsql(queryGenerator.whereItemsQuery(whereObj, options), expectation);
          },
        );
      };

      testsql(
        sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), queryVector),
        {
          [Op.lt]: 2,
        },
        {
          oracle: `VECTOR_DISTANCE("embedding", VECTOR('[1,2,3]')) < 2`,
        },
      );

      testsql(
        sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), new Float32Array([1, 2, 3])),
        {
          [Op.lt]: 2,
        },
        {
          oracle: `VECTOR_DISTANCE("embedding", VECTOR('[1,2,3]')) < 2`,
        },
      );

      testsql(
        sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), `VECTOR('[1,2,3]')`),
        {
          [Op.lt]: 2,
        },
        {
          oracle: `VECTOR_DISTANCE("embedding", VECTOR('[1,2,3]')) < 2`,
        },
      );

      testsql(
        sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), new Uint8Array([1, 2, 3])),
        {
          [Op.lt]: 2,
        },
        {
          oracle: `VECTOR_DISTANCE("embedding", VECTOR('[1,2,3]')) < 2`,
        },
      );

      it('throws when second argument is an unsupported integer typed array', () => {
        expect(() =>
          queryGenerator.whereItemsQuery(
            sql.where(sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), new Int8Array([1])), {
              [Op.lt]: 2,
            }),
          ),
        ).to.throw(Error, 'Invalid value received for the "where" option');
      });

      it('throws when second argument is not a vector input', () => {
        expect(() =>
          queryGenerator.whereItemsQuery(
            sql.where(sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), 'not-a-vector'), {
              [Op.lt]: 2,
            }),
          ),
        ).to.throw(Error, 'Invalid value received for the "where" option');
      });

      it('throws for non-finite vector array elements', () => {
        expect(() =>
          queryGenerator.whereItemsQuery(
            sql.where(sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), [1, Infinity, 3]), {
              [Op.lt]: 2,
            }),
          ),
        ).to.throw(Error, 'Invalid value received for the "where" option');
      });

      it('throws for malformed VECTOR literal strings', () => {
        expect(() =>
          queryGenerator.whereItemsQuery(
            sql.where(sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), `VECTR('[1,2,3]')`), {
              [Op.lt]: 2,
            }),
          ),
        ).to.throw(Error, 'Invalid value received for the "where" option');
      });

      it('throws for unsafe VECTOR literal strings', () => {
        for (const payload of [
          `VECTOR('[1,2,3]'); DROP TABLE users; --')`,
          `VECTOR('[1,2,3]') || 'x'`,
          `VECTOR_DISTANCE("embedding", VECTOR('[1,2,3]'))`,
        ]) {
          expect(() =>
            queryGenerator.whereItemsQuery(
              sql.where(sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), payload), {
                [Op.lt]: 2,
              }),
            ),
          ).to.throw(Error, 'Invalid value received for the "where" option');
        }
      });

      it('throws for malformed VECTOR literal payloads', () => {
        expect(() =>
          queryGenerator.whereItemsQuery(
            sql.where(
              sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), `VECTOR('[1,foo,3]')`),
              {
                [Op.lt]: 2,
              },
            ),
          ),
        ).to.throw(Error, 'Invalid value received for the "where" option');
      });

      it('throws when vector function has too few arguments', () => {
        expect(() =>
          queryGenerator.formatSqlExpression(sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'))),
        ).to.throw(Error, 'VECTOR_DISTANCE expects exactly 2 arguments');
      });

      it('throws when vector function has too many arguments', () => {
        expect(() =>
          queryGenerator.formatSqlExpression(
            sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), [1, 2, 3], [4, 5, 6]),
          ),
        ).to.throw(Error, 'VECTOR_DISTANCE expects exactly 2 arguments');
      });
    });

    describe('order by distance with limit', () => {
      const queryVector = [1, 2, 3, 4];

      const User = Support.sequelize.define(
        'User',
        {
          embedding: {
            type: DataTypes.VECTOR(4),
          },
        },
        {
          tableName: 'user',
        },
      );

      it('generates order by vector distance', () => {
        expectsql(
          queryGenerator.selectQuery(
            User.table,
            {
              model: User,
              attributes: ['embedding'],
              order: [sql.fn('VECTOR_DISTANCE', sql.attribute('embedding'), queryVector)],
              limit: 5,
            },
            User,
          ),
          {
            oracle: `SELECT "embedding" FROM "user" "User" ORDER BY VECTOR_DISTANCE("embedding", VECTOR('[1,2,3,4]')) OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;`,
          },
        );
      });
    });
  });
}
