
'use strict';

const Support   = require('../../support'),
  DataTypes = require('sequelize/lib/data-types'),
  expectsql = Support.expectsql,
  current   = Support.sequelize,
  sql       = current.dialect.queryGenerator,
  sinon = require('sinon');

if (current.dialect.name === 'oracle') {
  describe('createTable', () => {
    const FooUser = current.define('user', {
      intCol: {
        type: DataTypes.INTEGER.UNSIGNED,
        allowNull: false,
        defaultValue: 0
      }
    }, 
    {
      schema: 'foo',
      timestamps: false
    });

    describe('[Oracle Specific] QueryGenerator', () => {
      it('checks for values >=0', () => {
        expectsql(sql.createTableQuery(FooUser.getTableName(), sql.attributesToSQL(FooUser.rawAttributes), { }), {
          default: 'BEGIN EXECUTE IMMEDIATE \'CREATE TABLE "foo"."users" ("id" NUMBER(*,0) GENERATED BY DEFAULT ON NULL AS IDENTITY, "intCol" INTEGER DEFAULT 0 NOT NULL check("intCol" >= 0),PRIMARY KEY ("id"))\'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;' });
      });
    });
  });

  // Alter table for blob tries implicit type conversion if datatype is mentioned in SQL, which leads to failure.
  describe('changeColumn', () => {
    const Model = current.define('items', {
      blobCol: {
        type: DataTypes.BLOB
      }
    }, { timestamps: false });

    before(function() {
      this.stub = sinon.stub(current, 'query').resolvesArg(0);
    });

    beforeEach(function() {
      this.stub.resetHistory();
    });

    after(function() {
      this.stub.restore();
    });
    
    it('properly generate alter queries for BLOB', () => {
      return current.getQueryInterface().changeColumn(Model.getTableName(), 'blobCol', {
        type: DataTypes.BLOB,
        allowNull: false
      }).then(sql => {
        expectsql(sql, {
          oracle: 'DECLARE CONS_NAME VARCHAR2(200); BEGIN BEGIN EXECUTE IMMEDIATE \'ALTER TABLE "items" MODIFY "blobCol" NOT NULL\'; EXCEPTION WHEN OTHERS THEN IF SQLCODE = -1442 OR SQLCODE = -1451 THEN EXECUTE IMMEDIATE \'ALTER TABLE "items" MODIFY "blobCol" \'; ELSE RAISE; END IF; END; END;'
        });
      });
    });
  });
}