name: Draft unfinished PRs

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  checks: read
  contents: read

jobs:
  draft-unfinished-prs:
    name: Draft unfinished PRs
    runs-on: ubuntu-latest
    steps:
      - uses: sequelize/draft-unfinished-prs@dcded35052048b01a1c925cfd8fb7cda473f9b96
        with:
          dry-run: true
